language: cpp
sudo: false
compiler:
  - gcc
  - clang

env:
  global:
    - GCC_VERSION="4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #Build dependencies:
    - cmake
    - p7zip-full
    - g++-4.8
    #SFML dependencies:
    - libopenal-dev
    - libjpeg-dev
    - libglew-dev
    - libudev-dev
    - libxrandr-dev
    - libsndfile1-dev
    - libglu1-mesa-dev
    - libfreetype6-dev

#Activate X Virtual Framebuffer to allow tests to
#use SFML.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
#Get the correct version of gcc/g++
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
#Compile the tests only
  - mkdir .build-tests
  - cd .build-tests
  - cmake -DBUILD_GDJS=FALSE -DBUILD_IDE=FALSE -DBUILD_TESTS=TRUE -DNO_GUI=TRUE -DCMAKE_CXX_COMPILER=$(which $CXX) -DCMAKE_C_COMPILER=$(which $CC) ..
  - make -j 4
  - cd ..
#Install GDJS tests dependencies
  - cd GDJS/tests
  - npm install
  - cd ../..

script:
#GDJS game engine tests:
  - cd GDJS/tests
  - npm test
  - cd ../..
#GDCore and GDCpp game engine tests:
  - cd .build-tests
# - export LD_LIBRARY_PATH=$PWD/Binaries/Output/Release_Linux:$PWD/.build-tests/ExtLibs/SFML/lib:$LD_LIBRARY_PATH
  - Core/GDCore_tests
  - GDCpp/GDCpp_tests
  - Extensions/PathfindingBehavior/PathfindingBehavior_Runtime_tests
  - Extensions/LinkedObjects/LinkedObjects_Runtime_tests
